### ISSUE TITLE
libcnb-test: Need better error for container that cannot boot

### ISSUE THREAD

**Issue by schneems** [heroku/libcnb.rs#584] opened 2023-06-29 16:45 UTC
Context. I made a mistake in building my default process command and it won't boot:

```
$ docker run -it --rm --env PORT=9292 -p 9292:9292 my-image
bash: line 1: execbundleexec: command not found
```

Expected: My integration tests tell me that the container failed to boot directly
Actual:

```
thread 'test_default_app' panicked at 'called `Option::unwrap()` on a `None` value', buildpacks/ruby/tests/integration_test.rs:122:49
```

From this code:

```rust
fn request_container(
    container: &ContainerContext,
    port: u16,
    path: &str,
) -> Result<Response, Box<ureq::Error>> {
    let addr = container.address_for_port(port).unwrap(); // <== HERE
    let ip = addr.ip();
    let port = addr.port();
    let req = ureq::get(&format!("http://{ip}:{port}/{path}"));
    req.call().map_err(Box::new)
}
```

I would have expected the error to come up in `start_container`. Here's the full test code:

```rust
fn test_default_app() {
    TestRunner::default().build(
        BuildConfig::new("heroku/builder:22", "tests/fixtures/default_ruby")
        .buildpacks(vec![BuildpackReference::Crate]),
        |context| {
            assert_contains!(context.pack_stdout, "[Installing Ruby]");
            assert_contains!(
                context.pack_stdout,
                r#"$ BUNDLE_BIN="/layers/heroku_ruby/gems/bin" BUNDLE_CLEAN="1" BUNDLE_DEPLOYMENT="1" BUNDLE_GEMFILE="/workspace/Gemfile" BUNDLE_PATH="/layers/heroku_ruby/gems" BUNDLE_WITHOUT="development:test" bundle install"#);

            println!("{}", context.pack_stdout); // Needed to get full failure as `rebuild` truncates stdout
            assert_contains!(context.pack_stdout, "Installing webrick");

            let config = context.config.clone();
            context.rebuild(config, |rebuild_context| {
                assert_contains!(rebuild_context.pack_stdout, "Skipping 'bundle install', no changes found in /workspace/Gemfile, /workspace/Gemfile.lock, or user configured environment variables");

                rebuild_context.start_container(
                    ContainerConfig::new()
                        .env("PORT", TEST_PORT.to_string())
                        .expose_port(TEST_PORT),
                    |container| {
                        let response = call_root_until_boot(&container, TEST_PORT).unwrap();
                        let body = response.into_string().unwrap();

                        let server_logs = container.logs_now();
                        assert_contains!(server_logs.stderr, "WEBrick::HTTPServer#start");
                        assert_empty!(server_logs.stdout);

                        assert_contains!(body, "ruby_version");
                    },
                );
            });
        },
    );
}
```

**Comment by edmorley** [comment] 2023-08-17 14:02
(I discussed this with Richard a while ago in a 1:1, but documenting here for completeness)

There are two main types of failures that can happen when starting a container:
1. An error spawning the command
2. An error that occurs after the command was spawned (eg exiting non-zero)

libcnb.rs 0.13.0 (ie: prior to the recent fixes) already handled case (1) well - and would display an appropriate error message before even getting as far as the `address_for_port()` call.

In this specific case (`bash: line 1: execbundleexec: command not found`), whilst at first glance it seems to be of type (1) - it's actually of type (2). That is, the command being spawned is `bash`, and so the initial spawn was successful. Bash then soon after spawning exits non-zero (since the command it's being asked to run cannot be found), however, this is no different to say a web server taking 5 seconds to start and then eventually crashing and exiting non-zero (apart from the fact that bash starts and exits in a fraction of the time of course - but it's still not instant/related to spawning).

Therefore this issue is a duplicate of #482, for which there is now a PR open that will automatically output the container logs, improving the UX here.

**Closed by edmorley** 2023-08-17 14:02 UTC
Labels: libcnb-test
